apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.services.admin.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.images.admin.repository }}:{{ .Values.images.admin.tag }}"
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
          envFrom:
            - configMapRef:
                name: streamingapp-config
            - secretRef:
                name: streamingapp-secret
          readinessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
